import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from 'react-hot-toast';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        

<Toaster
  position="top-right"
  toastOptions={{
    style: {
      borderRadius: '8px',
      background: '#fff',
      color: '#333',
      fontSize: '14px',
      fontWeight: 500,
    },
    success: {
      style: {
        background: '#ecfdf5',
        color: '#065f46',
        border: '1px solid #34d399',
      },
      iconTheme: {
        primary: '#10b981',
        secondary: '#ecfdf5',
      },
    },
    error: {
      style: {
        background: '#fef2f2',
        color: '#991b1b',
        border: '1px solid #f87171',
      },
      iconTheme: {
        primary: '#ef4444',
        secondary: '#fef2f2',
      },
    },
  }}
/>

      </body>
    </html>
  );
}
